/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package openpolitica.jne.infogob.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Afiliacion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8171970671167653387L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Afiliacion\",\"namespace\":\"openpolitica.jne.infogob.data\",\"fields\":[{\"name\":\"org_politica\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"org_politica_estado\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"org_politica_tipo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"org_politica_alcance\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"org_politica_fecha_inscripcion\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"afiliacion_estado\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"afiliacion_inicio\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"afiliacion_representante\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"afiliacion_comite\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"afiliacion_cancelacion\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"cargos\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Cargo\",\"fields\":[{\"name\":\"cargo_nombre\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"cargo_periodo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Afiliacion> ENCODER =
      new BinaryMessageEncoder<Afiliacion>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Afiliacion> DECODER =
      new BinaryMessageDecoder<Afiliacion>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Afiliacion> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Afiliacion> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Afiliacion> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Afiliacion>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Afiliacion to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Afiliacion from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Afiliacion instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Afiliacion fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String org_politica;
   private java.lang.String org_politica_estado;
   private java.lang.String org_politica_tipo;
   private java.lang.String org_politica_alcance;
   private java.lang.String org_politica_fecha_inscripcion;
   private java.lang.String afiliacion_estado;
   private java.lang.String afiliacion_inicio;
   private java.lang.String afiliacion_representante;
   private java.lang.String afiliacion_comite;
   private java.lang.String afiliacion_cancelacion;
   private java.util.List<openpolitica.jne.infogob.data.Cargo> cargos;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Afiliacion() {}

  /**
   * All-args constructor.
   * @param org_politica The new value for org_politica
   * @param org_politica_estado The new value for org_politica_estado
   * @param org_politica_tipo The new value for org_politica_tipo
   * @param org_politica_alcance The new value for org_politica_alcance
   * @param org_politica_fecha_inscripcion The new value for org_politica_fecha_inscripcion
   * @param afiliacion_estado The new value for afiliacion_estado
   * @param afiliacion_inicio The new value for afiliacion_inicio
   * @param afiliacion_representante The new value for afiliacion_representante
   * @param afiliacion_comite The new value for afiliacion_comite
   * @param afiliacion_cancelacion The new value for afiliacion_cancelacion
   * @param cargos The new value for cargos
   */
  public Afiliacion(java.lang.String org_politica, java.lang.String org_politica_estado, java.lang.String org_politica_tipo, java.lang.String org_politica_alcance, java.lang.String org_politica_fecha_inscripcion, java.lang.String afiliacion_estado, java.lang.String afiliacion_inicio, java.lang.String afiliacion_representante, java.lang.String afiliacion_comite, java.lang.String afiliacion_cancelacion, java.util.List<openpolitica.jne.infogob.data.Cargo> cargos) {
    this.org_politica = org_politica;
    this.org_politica_estado = org_politica_estado;
    this.org_politica_tipo = org_politica_tipo;
    this.org_politica_alcance = org_politica_alcance;
    this.org_politica_fecha_inscripcion = org_politica_fecha_inscripcion;
    this.afiliacion_estado = afiliacion_estado;
    this.afiliacion_inicio = afiliacion_inicio;
    this.afiliacion_representante = afiliacion_representante;
    this.afiliacion_comite = afiliacion_comite;
    this.afiliacion_cancelacion = afiliacion_cancelacion;
    this.cargos = cargos;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return org_politica;
    case 1: return org_politica_estado;
    case 2: return org_politica_tipo;
    case 3: return org_politica_alcance;
    case 4: return org_politica_fecha_inscripcion;
    case 5: return afiliacion_estado;
    case 6: return afiliacion_inicio;
    case 7: return afiliacion_representante;
    case 8: return afiliacion_comite;
    case 9: return afiliacion_cancelacion;
    case 10: return cargos;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: org_politica = value$ != null ? value$.toString() : null; break;
    case 1: org_politica_estado = value$ != null ? value$.toString() : null; break;
    case 2: org_politica_tipo = value$ != null ? value$.toString() : null; break;
    case 3: org_politica_alcance = value$ != null ? value$.toString() : null; break;
    case 4: org_politica_fecha_inscripcion = value$ != null ? value$.toString() : null; break;
    case 5: afiliacion_estado = value$ != null ? value$.toString() : null; break;
    case 6: afiliacion_inicio = value$ != null ? value$.toString() : null; break;
    case 7: afiliacion_representante = value$ != null ? value$.toString() : null; break;
    case 8: afiliacion_comite = value$ != null ? value$.toString() : null; break;
    case 9: afiliacion_cancelacion = value$ != null ? value$.toString() : null; break;
    case 10: cargos = (java.util.List<openpolitica.jne.infogob.data.Cargo>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'org_politica' field.
   * @return The value of the 'org_politica' field.
   */
  public java.lang.String getOrgPolitica() {
    return org_politica;
  }


  /**
   * Sets the value of the 'org_politica' field.
   * @param value the value to set.
   */
  public void setOrgPolitica(java.lang.String value) {
    this.org_politica = value;
  }

  /**
   * Gets the value of the 'org_politica_estado' field.
   * @return The value of the 'org_politica_estado' field.
   */
  public java.lang.String getOrgPoliticaEstado() {
    return org_politica_estado;
  }


  /**
   * Sets the value of the 'org_politica_estado' field.
   * @param value the value to set.
   */
  public void setOrgPoliticaEstado(java.lang.String value) {
    this.org_politica_estado = value;
  }

  /**
   * Gets the value of the 'org_politica_tipo' field.
   * @return The value of the 'org_politica_tipo' field.
   */
  public java.lang.String getOrgPoliticaTipo() {
    return org_politica_tipo;
  }


  /**
   * Sets the value of the 'org_politica_tipo' field.
   * @param value the value to set.
   */
  public void setOrgPoliticaTipo(java.lang.String value) {
    this.org_politica_tipo = value;
  }

  /**
   * Gets the value of the 'org_politica_alcance' field.
   * @return The value of the 'org_politica_alcance' field.
   */
  public java.lang.String getOrgPoliticaAlcance() {
    return org_politica_alcance;
  }


  /**
   * Sets the value of the 'org_politica_alcance' field.
   * @param value the value to set.
   */
  public void setOrgPoliticaAlcance(java.lang.String value) {
    this.org_politica_alcance = value;
  }

  /**
   * Gets the value of the 'org_politica_fecha_inscripcion' field.
   * @return The value of the 'org_politica_fecha_inscripcion' field.
   */
  public java.lang.String getOrgPoliticaFechaInscripcion() {
    return org_politica_fecha_inscripcion;
  }


  /**
   * Sets the value of the 'org_politica_fecha_inscripcion' field.
   * @param value the value to set.
   */
  public void setOrgPoliticaFechaInscripcion(java.lang.String value) {
    this.org_politica_fecha_inscripcion = value;
  }

  /**
   * Gets the value of the 'afiliacion_estado' field.
   * @return The value of the 'afiliacion_estado' field.
   */
  public java.lang.String getAfiliacionEstado() {
    return afiliacion_estado;
  }


  /**
   * Sets the value of the 'afiliacion_estado' field.
   * @param value the value to set.
   */
  public void setAfiliacionEstado(java.lang.String value) {
    this.afiliacion_estado = value;
  }

  /**
   * Gets the value of the 'afiliacion_inicio' field.
   * @return The value of the 'afiliacion_inicio' field.
   */
  public java.lang.String getAfiliacionInicio() {
    return afiliacion_inicio;
  }


  /**
   * Sets the value of the 'afiliacion_inicio' field.
   * @param value the value to set.
   */
  public void setAfiliacionInicio(java.lang.String value) {
    this.afiliacion_inicio = value;
  }

  /**
   * Gets the value of the 'afiliacion_representante' field.
   * @return The value of the 'afiliacion_representante' field.
   */
  public java.lang.String getAfiliacionRepresentante() {
    return afiliacion_representante;
  }


  /**
   * Sets the value of the 'afiliacion_representante' field.
   * @param value the value to set.
   */
  public void setAfiliacionRepresentante(java.lang.String value) {
    this.afiliacion_representante = value;
  }

  /**
   * Gets the value of the 'afiliacion_comite' field.
   * @return The value of the 'afiliacion_comite' field.
   */
  public java.lang.String getAfiliacionComite() {
    return afiliacion_comite;
  }


  /**
   * Sets the value of the 'afiliacion_comite' field.
   * @param value the value to set.
   */
  public void setAfiliacionComite(java.lang.String value) {
    this.afiliacion_comite = value;
  }

  /**
   * Gets the value of the 'afiliacion_cancelacion' field.
   * @return The value of the 'afiliacion_cancelacion' field.
   */
  public java.lang.String getAfiliacionCancelacion() {
    return afiliacion_cancelacion;
  }


  /**
   * Sets the value of the 'afiliacion_cancelacion' field.
   * @param value the value to set.
   */
  public void setAfiliacionCancelacion(java.lang.String value) {
    this.afiliacion_cancelacion = value;
  }

  /**
   * Gets the value of the 'cargos' field.
   * @return The value of the 'cargos' field.
   */
  public java.util.List<openpolitica.jne.infogob.data.Cargo> getCargos() {
    return cargos;
  }


  /**
   * Sets the value of the 'cargos' field.
   * @param value the value to set.
   */
  public void setCargos(java.util.List<openpolitica.jne.infogob.data.Cargo> value) {
    this.cargos = value;
  }

  /**
   * Creates a new Afiliacion RecordBuilder.
   * @return A new Afiliacion RecordBuilder
   */
  public static openpolitica.jne.infogob.data.Afiliacion.Builder newBuilder() {
    return new openpolitica.jne.infogob.data.Afiliacion.Builder();
  }

  /**
   * Creates a new Afiliacion RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Afiliacion RecordBuilder
   */
  public static openpolitica.jne.infogob.data.Afiliacion.Builder newBuilder(openpolitica.jne.infogob.data.Afiliacion.Builder other) {
    if (other == null) {
      return new openpolitica.jne.infogob.data.Afiliacion.Builder();
    } else {
      return new openpolitica.jne.infogob.data.Afiliacion.Builder(other);
    }
  }

  /**
   * Creates a new Afiliacion RecordBuilder by copying an existing Afiliacion instance.
   * @param other The existing instance to copy.
   * @return A new Afiliacion RecordBuilder
   */
  public static openpolitica.jne.infogob.data.Afiliacion.Builder newBuilder(openpolitica.jne.infogob.data.Afiliacion other) {
    if (other == null) {
      return new openpolitica.jne.infogob.data.Afiliacion.Builder();
    } else {
      return new openpolitica.jne.infogob.data.Afiliacion.Builder(other);
    }
  }

  /**
   * RecordBuilder for Afiliacion instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Afiliacion>
    implements org.apache.avro.data.RecordBuilder<Afiliacion> {

    private java.lang.String org_politica;
    private java.lang.String org_politica_estado;
    private java.lang.String org_politica_tipo;
    private java.lang.String org_politica_alcance;
    private java.lang.String org_politica_fecha_inscripcion;
    private java.lang.String afiliacion_estado;
    private java.lang.String afiliacion_inicio;
    private java.lang.String afiliacion_representante;
    private java.lang.String afiliacion_comite;
    private java.lang.String afiliacion_cancelacion;
    private java.util.List<openpolitica.jne.infogob.data.Cargo> cargos;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(openpolitica.jne.infogob.data.Afiliacion.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.org_politica)) {
        this.org_politica = data().deepCopy(fields()[0].schema(), other.org_politica);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.org_politica_estado)) {
        this.org_politica_estado = data().deepCopy(fields()[1].schema(), other.org_politica_estado);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.org_politica_tipo)) {
        this.org_politica_tipo = data().deepCopy(fields()[2].schema(), other.org_politica_tipo);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.org_politica_alcance)) {
        this.org_politica_alcance = data().deepCopy(fields()[3].schema(), other.org_politica_alcance);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.org_politica_fecha_inscripcion)) {
        this.org_politica_fecha_inscripcion = data().deepCopy(fields()[4].schema(), other.org_politica_fecha_inscripcion);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.afiliacion_estado)) {
        this.afiliacion_estado = data().deepCopy(fields()[5].schema(), other.afiliacion_estado);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.afiliacion_inicio)) {
        this.afiliacion_inicio = data().deepCopy(fields()[6].schema(), other.afiliacion_inicio);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.afiliacion_representante)) {
        this.afiliacion_representante = data().deepCopy(fields()[7].schema(), other.afiliacion_representante);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.afiliacion_comite)) {
        this.afiliacion_comite = data().deepCopy(fields()[8].schema(), other.afiliacion_comite);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.afiliacion_cancelacion)) {
        this.afiliacion_cancelacion = data().deepCopy(fields()[9].schema(), other.afiliacion_cancelacion);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.cargos)) {
        this.cargos = data().deepCopy(fields()[10].schema(), other.cargos);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing Afiliacion instance
     * @param other The existing instance to copy.
     */
    private Builder(openpolitica.jne.infogob.data.Afiliacion other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.org_politica)) {
        this.org_politica = data().deepCopy(fields()[0].schema(), other.org_politica);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.org_politica_estado)) {
        this.org_politica_estado = data().deepCopy(fields()[1].schema(), other.org_politica_estado);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.org_politica_tipo)) {
        this.org_politica_tipo = data().deepCopy(fields()[2].schema(), other.org_politica_tipo);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.org_politica_alcance)) {
        this.org_politica_alcance = data().deepCopy(fields()[3].schema(), other.org_politica_alcance);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.org_politica_fecha_inscripcion)) {
        this.org_politica_fecha_inscripcion = data().deepCopy(fields()[4].schema(), other.org_politica_fecha_inscripcion);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.afiliacion_estado)) {
        this.afiliacion_estado = data().deepCopy(fields()[5].schema(), other.afiliacion_estado);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.afiliacion_inicio)) {
        this.afiliacion_inicio = data().deepCopy(fields()[6].schema(), other.afiliacion_inicio);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.afiliacion_representante)) {
        this.afiliacion_representante = data().deepCopy(fields()[7].schema(), other.afiliacion_representante);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.afiliacion_comite)) {
        this.afiliacion_comite = data().deepCopy(fields()[8].schema(), other.afiliacion_comite);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.afiliacion_cancelacion)) {
        this.afiliacion_cancelacion = data().deepCopy(fields()[9].schema(), other.afiliacion_cancelacion);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.cargos)) {
        this.cargos = data().deepCopy(fields()[10].schema(), other.cargos);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'org_politica' field.
      * @return The value.
      */
    public java.lang.String getOrgPolitica() {
      return org_politica;
    }


    /**
      * Sets the value of the 'org_politica' field.
      * @param value The value of 'org_politica'.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder setOrgPolitica(java.lang.String value) {
      validate(fields()[0], value);
      this.org_politica = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'org_politica' field has been set.
      * @return True if the 'org_politica' field has been set, false otherwise.
      */
    public boolean hasOrgPolitica() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'org_politica' field.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder clearOrgPolitica() {
      org_politica = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'org_politica_estado' field.
      * @return The value.
      */
    public java.lang.String getOrgPoliticaEstado() {
      return org_politica_estado;
    }


    /**
      * Sets the value of the 'org_politica_estado' field.
      * @param value The value of 'org_politica_estado'.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder setOrgPoliticaEstado(java.lang.String value) {
      validate(fields()[1], value);
      this.org_politica_estado = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'org_politica_estado' field has been set.
      * @return True if the 'org_politica_estado' field has been set, false otherwise.
      */
    public boolean hasOrgPoliticaEstado() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'org_politica_estado' field.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder clearOrgPoliticaEstado() {
      org_politica_estado = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'org_politica_tipo' field.
      * @return The value.
      */
    public java.lang.String getOrgPoliticaTipo() {
      return org_politica_tipo;
    }


    /**
      * Sets the value of the 'org_politica_tipo' field.
      * @param value The value of 'org_politica_tipo'.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder setOrgPoliticaTipo(java.lang.String value) {
      validate(fields()[2], value);
      this.org_politica_tipo = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'org_politica_tipo' field has been set.
      * @return True if the 'org_politica_tipo' field has been set, false otherwise.
      */
    public boolean hasOrgPoliticaTipo() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'org_politica_tipo' field.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder clearOrgPoliticaTipo() {
      org_politica_tipo = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'org_politica_alcance' field.
      * @return The value.
      */
    public java.lang.String getOrgPoliticaAlcance() {
      return org_politica_alcance;
    }


    /**
      * Sets the value of the 'org_politica_alcance' field.
      * @param value The value of 'org_politica_alcance'.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder setOrgPoliticaAlcance(java.lang.String value) {
      validate(fields()[3], value);
      this.org_politica_alcance = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'org_politica_alcance' field has been set.
      * @return True if the 'org_politica_alcance' field has been set, false otherwise.
      */
    public boolean hasOrgPoliticaAlcance() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'org_politica_alcance' field.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder clearOrgPoliticaAlcance() {
      org_politica_alcance = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'org_politica_fecha_inscripcion' field.
      * @return The value.
      */
    public java.lang.String getOrgPoliticaFechaInscripcion() {
      return org_politica_fecha_inscripcion;
    }


    /**
      * Sets the value of the 'org_politica_fecha_inscripcion' field.
      * @param value The value of 'org_politica_fecha_inscripcion'.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder setOrgPoliticaFechaInscripcion(java.lang.String value) {
      validate(fields()[4], value);
      this.org_politica_fecha_inscripcion = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'org_politica_fecha_inscripcion' field has been set.
      * @return True if the 'org_politica_fecha_inscripcion' field has been set, false otherwise.
      */
    public boolean hasOrgPoliticaFechaInscripcion() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'org_politica_fecha_inscripcion' field.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder clearOrgPoliticaFechaInscripcion() {
      org_politica_fecha_inscripcion = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'afiliacion_estado' field.
      * @return The value.
      */
    public java.lang.String getAfiliacionEstado() {
      return afiliacion_estado;
    }


    /**
      * Sets the value of the 'afiliacion_estado' field.
      * @param value The value of 'afiliacion_estado'.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder setAfiliacionEstado(java.lang.String value) {
      validate(fields()[5], value);
      this.afiliacion_estado = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'afiliacion_estado' field has been set.
      * @return True if the 'afiliacion_estado' field has been set, false otherwise.
      */
    public boolean hasAfiliacionEstado() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'afiliacion_estado' field.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder clearAfiliacionEstado() {
      afiliacion_estado = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'afiliacion_inicio' field.
      * @return The value.
      */
    public java.lang.String getAfiliacionInicio() {
      return afiliacion_inicio;
    }


    /**
      * Sets the value of the 'afiliacion_inicio' field.
      * @param value The value of 'afiliacion_inicio'.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder setAfiliacionInicio(java.lang.String value) {
      validate(fields()[6], value);
      this.afiliacion_inicio = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'afiliacion_inicio' field has been set.
      * @return True if the 'afiliacion_inicio' field has been set, false otherwise.
      */
    public boolean hasAfiliacionInicio() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'afiliacion_inicio' field.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder clearAfiliacionInicio() {
      afiliacion_inicio = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'afiliacion_representante' field.
      * @return The value.
      */
    public java.lang.String getAfiliacionRepresentante() {
      return afiliacion_representante;
    }


    /**
      * Sets the value of the 'afiliacion_representante' field.
      * @param value The value of 'afiliacion_representante'.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder setAfiliacionRepresentante(java.lang.String value) {
      validate(fields()[7], value);
      this.afiliacion_representante = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'afiliacion_representante' field has been set.
      * @return True if the 'afiliacion_representante' field has been set, false otherwise.
      */
    public boolean hasAfiliacionRepresentante() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'afiliacion_representante' field.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder clearAfiliacionRepresentante() {
      afiliacion_representante = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'afiliacion_comite' field.
      * @return The value.
      */
    public java.lang.String getAfiliacionComite() {
      return afiliacion_comite;
    }


    /**
      * Sets the value of the 'afiliacion_comite' field.
      * @param value The value of 'afiliacion_comite'.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder setAfiliacionComite(java.lang.String value) {
      validate(fields()[8], value);
      this.afiliacion_comite = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'afiliacion_comite' field has been set.
      * @return True if the 'afiliacion_comite' field has been set, false otherwise.
      */
    public boolean hasAfiliacionComite() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'afiliacion_comite' field.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder clearAfiliacionComite() {
      afiliacion_comite = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'afiliacion_cancelacion' field.
      * @return The value.
      */
    public java.lang.String getAfiliacionCancelacion() {
      return afiliacion_cancelacion;
    }


    /**
      * Sets the value of the 'afiliacion_cancelacion' field.
      * @param value The value of 'afiliacion_cancelacion'.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder setAfiliacionCancelacion(java.lang.String value) {
      validate(fields()[9], value);
      this.afiliacion_cancelacion = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'afiliacion_cancelacion' field has been set.
      * @return True if the 'afiliacion_cancelacion' field has been set, false otherwise.
      */
    public boolean hasAfiliacionCancelacion() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'afiliacion_cancelacion' field.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder clearAfiliacionCancelacion() {
      afiliacion_cancelacion = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'cargos' field.
      * @return The value.
      */
    public java.util.List<openpolitica.jne.infogob.data.Cargo> getCargos() {
      return cargos;
    }


    /**
      * Sets the value of the 'cargos' field.
      * @param value The value of 'cargos'.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder setCargos(java.util.List<openpolitica.jne.infogob.data.Cargo> value) {
      validate(fields()[10], value);
      this.cargos = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'cargos' field has been set.
      * @return True if the 'cargos' field has been set, false otherwise.
      */
    public boolean hasCargos() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'cargos' field.
      * @return This builder.
      */
    public openpolitica.jne.infogob.data.Afiliacion.Builder clearCargos() {
      cargos = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Afiliacion build() {
      try {
        Afiliacion record = new Afiliacion();
        record.org_politica = fieldSetFlags()[0] ? this.org_politica : (java.lang.String) defaultValue(fields()[0]);
        record.org_politica_estado = fieldSetFlags()[1] ? this.org_politica_estado : (java.lang.String) defaultValue(fields()[1]);
        record.org_politica_tipo = fieldSetFlags()[2] ? this.org_politica_tipo : (java.lang.String) defaultValue(fields()[2]);
        record.org_politica_alcance = fieldSetFlags()[3] ? this.org_politica_alcance : (java.lang.String) defaultValue(fields()[3]);
        record.org_politica_fecha_inscripcion = fieldSetFlags()[4] ? this.org_politica_fecha_inscripcion : (java.lang.String) defaultValue(fields()[4]);
        record.afiliacion_estado = fieldSetFlags()[5] ? this.afiliacion_estado : (java.lang.String) defaultValue(fields()[5]);
        record.afiliacion_inicio = fieldSetFlags()[6] ? this.afiliacion_inicio : (java.lang.String) defaultValue(fields()[6]);
        record.afiliacion_representante = fieldSetFlags()[7] ? this.afiliacion_representante : (java.lang.String) defaultValue(fields()[7]);
        record.afiliacion_comite = fieldSetFlags()[8] ? this.afiliacion_comite : (java.lang.String) defaultValue(fields()[8]);
        record.afiliacion_cancelacion = fieldSetFlags()[9] ? this.afiliacion_cancelacion : (java.lang.String) defaultValue(fields()[9]);
        record.cargos = fieldSetFlags()[10] ? this.cargos : (java.util.List<openpolitica.jne.infogob.data.Cargo>) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Afiliacion>
    WRITER$ = (org.apache.avro.io.DatumWriter<Afiliacion>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Afiliacion>
    READER$ = (org.apache.avro.io.DatumReader<Afiliacion>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.org_politica);

    out.writeString(this.org_politica_estado);

    out.writeString(this.org_politica_tipo);

    out.writeString(this.org_politica_alcance);

    if (this.org_politica_fecha_inscripcion == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.org_politica_fecha_inscripcion);
    }

    out.writeString(this.afiliacion_estado);

    out.writeString(this.afiliacion_inicio);

    out.writeString(this.afiliacion_representante);

    if (this.afiliacion_comite == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.afiliacion_comite);
    }

    if (this.afiliacion_cancelacion == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.afiliacion_cancelacion);
    }

    long size0 = this.cargos.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (openpolitica.jne.infogob.data.Cargo e0: this.cargos) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.org_politica = in.readString();

      this.org_politica_estado = in.readString();

      this.org_politica_tipo = in.readString();

      this.org_politica_alcance = in.readString();

      if (in.readIndex() != 0) {
        in.readNull();
        this.org_politica_fecha_inscripcion = null;
      } else {
        this.org_politica_fecha_inscripcion = in.readString();
      }

      this.afiliacion_estado = in.readString();

      this.afiliacion_inicio = in.readString();

      this.afiliacion_representante = in.readString();

      if (in.readIndex() != 0) {
        in.readNull();
        this.afiliacion_comite = null;
      } else {
        this.afiliacion_comite = in.readString();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.afiliacion_cancelacion = null;
      } else {
        this.afiliacion_cancelacion = in.readString();
      }

      long size0 = in.readArrayStart();
      java.util.List<openpolitica.jne.infogob.data.Cargo> a0 = this.cargos;
      if (a0 == null) {
        a0 = new SpecificData.Array<openpolitica.jne.infogob.data.Cargo>((int)size0, SCHEMA$.getField("cargos").schema());
        this.cargos = a0;
      } else a0.clear();
      SpecificData.Array<openpolitica.jne.infogob.data.Cargo> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<openpolitica.jne.infogob.data.Cargo>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          openpolitica.jne.infogob.data.Cargo e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new openpolitica.jne.infogob.data.Cargo();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.org_politica = in.readString();
          break;

        case 1:
          this.org_politica_estado = in.readString();
          break;

        case 2:
          this.org_politica_tipo = in.readString();
          break;

        case 3:
          this.org_politica_alcance = in.readString();
          break;

        case 4:
          if (in.readIndex() != 0) {
            in.readNull();
            this.org_politica_fecha_inscripcion = null;
          } else {
            this.org_politica_fecha_inscripcion = in.readString();
          }
          break;

        case 5:
          this.afiliacion_estado = in.readString();
          break;

        case 6:
          this.afiliacion_inicio = in.readString();
          break;

        case 7:
          this.afiliacion_representante = in.readString();
          break;

        case 8:
          if (in.readIndex() != 0) {
            in.readNull();
            this.afiliacion_comite = null;
          } else {
            this.afiliacion_comite = in.readString();
          }
          break;

        case 9:
          if (in.readIndex() != 0) {
            in.readNull();
            this.afiliacion_cancelacion = null;
          } else {
            this.afiliacion_cancelacion = in.readString();
          }
          break;

        case 10:
          long size0 = in.readArrayStart();
          java.util.List<openpolitica.jne.infogob.data.Cargo> a0 = this.cargos;
          if (a0 == null) {
            a0 = new SpecificData.Array<openpolitica.jne.infogob.data.Cargo>((int)size0, SCHEMA$.getField("cargos").schema());
            this.cargos = a0;
          } else a0.clear();
          SpecificData.Array<openpolitica.jne.infogob.data.Cargo> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<openpolitica.jne.infogob.data.Cargo>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              openpolitica.jne.infogob.data.Cargo e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new openpolitica.jne.infogob.data.Cargo();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










