/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package openpolitica.jne.plataformaelectoral.data;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EducacionPostgrado extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7289367623978840225L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EducacionPostgrado\",\"namespace\":\"openpolitica.jne.elecciones.data\",\"fields\":[{\"name\":\"centro_estudio\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"TXCENESTUDIOPOSGRADO\"},{\"name\":\"especialidad\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"TXESPECIALIDADPOSGRADO\"},{\"name\":\"postgrado_anio\",\"type\":[\"int\",\"null\"]},{\"name\":\"concluida\",\"type\":[\"boolean\",\"null\"],\"doc\":\"SI/NO, TXCONCLUYO\"},{\"name\":\"egresado\",\"type\":[\"boolean\",\"null\"],\"doc\":\"SI/NO, TXEGRESADO\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EducacionPostgrado> ENCODER =
      new BinaryMessageEncoder<EducacionPostgrado>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EducacionPostgrado> DECODER =
      new BinaryMessageDecoder<EducacionPostgrado>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EducacionPostgrado> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EducacionPostgrado> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EducacionPostgrado> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EducacionPostgrado>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EducacionPostgrado to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EducacionPostgrado from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EducacionPostgrado instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EducacionPostgrado fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** TXCENESTUDIOPOSGRADO */
   private java.lang.String centro_estudio;
  /** TXESPECIALIDADPOSGRADO */
   private java.lang.String especialidad;
   private java.lang.Integer postgrado_anio;
  /** SI/NO, TXCONCLUYO */
   private java.lang.Boolean concluida;
  /** SI/NO, TXEGRESADO */
   private java.lang.Boolean egresado;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EducacionPostgrado() {}

  /**
   * All-args constructor.
   * @param centro_estudio TXCENESTUDIOPOSGRADO
   * @param especialidad TXESPECIALIDADPOSGRADO
   * @param postgrado_anio The new value for postgrado_anio
   * @param concluida SI/NO, TXCONCLUYO
   * @param egresado SI/NO, TXEGRESADO
   */
  public EducacionPostgrado(java.lang.String centro_estudio, java.lang.String especialidad, java.lang.Integer postgrado_anio, java.lang.Boolean concluida, java.lang.Boolean egresado) {
    this.centro_estudio = centro_estudio;
    this.especialidad = especialidad;
    this.postgrado_anio = postgrado_anio;
    this.concluida = concluida;
    this.egresado = egresado;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return centro_estudio;
    case 1: return especialidad;
    case 2: return postgrado_anio;
    case 3: return concluida;
    case 4: return egresado;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: centro_estudio = value$ != null ? value$.toString() : null; break;
    case 1: especialidad = value$ != null ? value$.toString() : null; break;
    case 2: postgrado_anio = (java.lang.Integer)value$; break;
    case 3: concluida = (java.lang.Boolean)value$; break;
    case 4: egresado = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'centro_estudio' field.
   * @return TXCENESTUDIOPOSGRADO
   */
  public java.lang.String getCentroEstudio() {
    return centro_estudio;
  }


  /**
   * Sets the value of the 'centro_estudio' field.
   * TXCENESTUDIOPOSGRADO
   * @param value the value to set.
   */
  public void setCentroEstudio(java.lang.String value) {
    this.centro_estudio = value;
  }

  /**
   * Gets the value of the 'especialidad' field.
   * @return TXESPECIALIDADPOSGRADO
   */
  public java.lang.String getEspecialidad() {
    return especialidad;
  }


  /**
   * Sets the value of the 'especialidad' field.
   * TXESPECIALIDADPOSGRADO
   * @param value the value to set.
   */
  public void setEspecialidad(java.lang.String value) {
    this.especialidad = value;
  }

  /**
   * Gets the value of the 'postgrado_anio' field.
   * @return The value of the 'postgrado_anio' field.
   */
  public java.lang.Integer getPostgradoAnio() {
    return postgrado_anio;
  }


  /**
   * Sets the value of the 'postgrado_anio' field.
   * @param value the value to set.
   */
  public void setPostgradoAnio(java.lang.Integer value) {
    this.postgrado_anio = value;
  }

  /**
   * Gets the value of the 'concluida' field.
   * @return SI/NO, TXCONCLUYO
   */
  public java.lang.Boolean getConcluida() {
    return concluida;
  }


  /**
   * Sets the value of the 'concluida' field.
   * SI/NO, TXCONCLUYO
   * @param value the value to set.
   */
  public void setConcluida(java.lang.Boolean value) {
    this.concluida = value;
  }

  /**
   * Gets the value of the 'egresado' field.
   * @return SI/NO, TXEGRESADO
   */
  public java.lang.Boolean getEgresado() {
    return egresado;
  }


  /**
   * Sets the value of the 'egresado' field.
   * SI/NO, TXEGRESADO
   * @param value the value to set.
   */
  public void setEgresado(java.lang.Boolean value) {
    this.egresado = value;
  }

  /**
   * Creates a new EducacionPostgrado RecordBuilder.
   * @return A new EducacionPostgrado RecordBuilder
   */
  public static openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder newBuilder() {
    return new openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder();
  }

  /**
   * Creates a new EducacionPostgrado RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EducacionPostgrado RecordBuilder
   */
  public static openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder newBuilder(openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder other) {
    if (other == null) {
      return new openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder();
    } else {
      return new openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder(other);
    }
  }

  /**
   * Creates a new EducacionPostgrado RecordBuilder by copying an existing EducacionPostgrado instance.
   * @param other The existing instance to copy.
   * @return A new EducacionPostgrado RecordBuilder
   */
  public static openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder newBuilder(openpolitica.jne.plataformaelectoral.data.EducacionPostgrado other) {
    if (other == null) {
      return new openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder();
    } else {
      return new openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder(other);
    }
  }

  /**
   * RecordBuilder for EducacionPostgrado instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EducacionPostgrado>
    implements org.apache.avro.data.RecordBuilder<EducacionPostgrado> {

    /** TXCENESTUDIOPOSGRADO */
    private java.lang.String centro_estudio;
    /** TXESPECIALIDADPOSGRADO */
    private java.lang.String especialidad;
    private java.lang.Integer postgrado_anio;
    /** SI/NO, TXCONCLUYO */
    private java.lang.Boolean concluida;
    /** SI/NO, TXEGRESADO */
    private java.lang.Boolean egresado;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.centro_estudio)) {
        this.centro_estudio = data().deepCopy(fields()[0].schema(), other.centro_estudio);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.especialidad)) {
        this.especialidad = data().deepCopy(fields()[1].schema(), other.especialidad);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.postgrado_anio)) {
        this.postgrado_anio = data().deepCopy(fields()[2].schema(), other.postgrado_anio);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.concluida)) {
        this.concluida = data().deepCopy(fields()[3].schema(), other.concluida);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.egresado)) {
        this.egresado = data().deepCopy(fields()[4].schema(), other.egresado);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing EducacionPostgrado instance
     * @param other The existing instance to copy.
     */
    private Builder(openpolitica.jne.plataformaelectoral.data.EducacionPostgrado other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.centro_estudio)) {
        this.centro_estudio = data().deepCopy(fields()[0].schema(), other.centro_estudio);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.especialidad)) {
        this.especialidad = data().deepCopy(fields()[1].schema(), other.especialidad);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.postgrado_anio)) {
        this.postgrado_anio = data().deepCopy(fields()[2].schema(), other.postgrado_anio);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.concluida)) {
        this.concluida = data().deepCopy(fields()[3].schema(), other.concluida);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.egresado)) {
        this.egresado = data().deepCopy(fields()[4].schema(), other.egresado);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'centro_estudio' field.
      * TXCENESTUDIOPOSGRADO
      * @return The value.
      */
    public java.lang.String getCentroEstudio() {
      return centro_estudio;
    }


    /**
      * Sets the value of the 'centro_estudio' field.
      * TXCENESTUDIOPOSGRADO
      * @param value The value of 'centro_estudio'.
      * @return This builder.
      */
    public openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder setCentroEstudio(java.lang.String value) {
      validate(fields()[0], value);
      this.centro_estudio = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'centro_estudio' field has been set.
      * TXCENESTUDIOPOSGRADO
      * @return True if the 'centro_estudio' field has been set, false otherwise.
      */
    public boolean hasCentroEstudio() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'centro_estudio' field.
      * TXCENESTUDIOPOSGRADO
      * @return This builder.
      */
    public openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder clearCentroEstudio() {
      centro_estudio = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'especialidad' field.
      * TXESPECIALIDADPOSGRADO
      * @return The value.
      */
    public java.lang.String getEspecialidad() {
      return especialidad;
    }


    /**
      * Sets the value of the 'especialidad' field.
      * TXESPECIALIDADPOSGRADO
      * @param value The value of 'especialidad'.
      * @return This builder.
      */
    public openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder setEspecialidad(java.lang.String value) {
      validate(fields()[1], value);
      this.especialidad = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'especialidad' field has been set.
      * TXESPECIALIDADPOSGRADO
      * @return True if the 'especialidad' field has been set, false otherwise.
      */
    public boolean hasEspecialidad() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'especialidad' field.
      * TXESPECIALIDADPOSGRADO
      * @return This builder.
      */
    public openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder clearEspecialidad() {
      especialidad = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'postgrado_anio' field.
      * @return The value.
      */
    public java.lang.Integer getPostgradoAnio() {
      return postgrado_anio;
    }


    /**
      * Sets the value of the 'postgrado_anio' field.
      * @param value The value of 'postgrado_anio'.
      * @return This builder.
      */
    public openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder setPostgradoAnio(java.lang.Integer value) {
      validate(fields()[2], value);
      this.postgrado_anio = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'postgrado_anio' field has been set.
      * @return True if the 'postgrado_anio' field has been set, false otherwise.
      */
    public boolean hasPostgradoAnio() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'postgrado_anio' field.
      * @return This builder.
      */
    public openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder clearPostgradoAnio() {
      postgrado_anio = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'concluida' field.
      * SI/NO, TXCONCLUYO
      * @return The value.
      */
    public java.lang.Boolean getConcluida() {
      return concluida;
    }


    /**
      * Sets the value of the 'concluida' field.
      * SI/NO, TXCONCLUYO
      * @param value The value of 'concluida'.
      * @return This builder.
      */
    public openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder setConcluida(java.lang.Boolean value) {
      validate(fields()[3], value);
      this.concluida = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'concluida' field has been set.
      * SI/NO, TXCONCLUYO
      * @return True if the 'concluida' field has been set, false otherwise.
      */
    public boolean hasConcluida() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'concluida' field.
      * SI/NO, TXCONCLUYO
      * @return This builder.
      */
    public openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder clearConcluida() {
      concluida = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'egresado' field.
      * SI/NO, TXEGRESADO
      * @return The value.
      */
    public java.lang.Boolean getEgresado() {
      return egresado;
    }


    /**
      * Sets the value of the 'egresado' field.
      * SI/NO, TXEGRESADO
      * @param value The value of 'egresado'.
      * @return This builder.
      */
    public openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder setEgresado(java.lang.Boolean value) {
      validate(fields()[4], value);
      this.egresado = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'egresado' field has been set.
      * SI/NO, TXEGRESADO
      * @return True if the 'egresado' field has been set, false otherwise.
      */
    public boolean hasEgresado() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'egresado' field.
      * SI/NO, TXEGRESADO
      * @return This builder.
      */
    public openpolitica.jne.plataformaelectoral.data.EducacionPostgrado.Builder clearEgresado() {
      egresado = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EducacionPostgrado build() {
      try {
        EducacionPostgrado record = new EducacionPostgrado();
        record.centro_estudio = fieldSetFlags()[0] ? this.centro_estudio : (java.lang.String) defaultValue(fields()[0]);
        record.especialidad = fieldSetFlags()[1] ? this.especialidad : (java.lang.String) defaultValue(fields()[1]);
        record.postgrado_anio = fieldSetFlags()[2] ? this.postgrado_anio : (java.lang.Integer) defaultValue(fields()[2]);
        record.concluida = fieldSetFlags()[3] ? this.concluida : (java.lang.Boolean) defaultValue(fields()[3]);
        record.egresado = fieldSetFlags()[4] ? this.egresado : (java.lang.Boolean) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EducacionPostgrado>
    WRITER$ = (org.apache.avro.io.DatumWriter<EducacionPostgrado>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EducacionPostgrado>
    READER$ = (org.apache.avro.io.DatumReader<EducacionPostgrado>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.centro_estudio);

    out.writeString(this.especialidad);

    if (this.postgrado_anio == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.postgrado_anio);
    }

    if (this.concluida == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeBoolean(this.concluida);
    }

    if (this.egresado == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeBoolean(this.egresado);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.centro_estudio = in.readString();

      this.especialidad = in.readString();

      if (in.readIndex() != 0) {
        in.readNull();
        this.postgrado_anio = null;
      } else {
        this.postgrado_anio = in.readInt();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.concluida = null;
      } else {
        this.concluida = in.readBoolean();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.egresado = null;
      } else {
        this.egresado = in.readBoolean();
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.centro_estudio = in.readString();
          break;

        case 1:
          this.especialidad = in.readString();
          break;

        case 2:
          if (in.readIndex() != 0) {
            in.readNull();
            this.postgrado_anio = null;
          } else {
            this.postgrado_anio = in.readInt();
          }
          break;

        case 3:
          if (in.readIndex() != 0) {
            in.readNull();
            this.concluida = null;
          } else {
            this.concluida = in.readBoolean();
          }
          break;

        case 4:
          if (in.readIndex() != 0) {
            in.readNull();
            this.egresado = null;
          } else {
            this.egresado = in.readBoolean();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










