/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package openpolitica.jne.elecciones.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BienInmueble extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6429252139058919302L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BienInmueble\",\"namespace\":\"openpolitica.jne.elecciones.data\",\"fields\":[{\"name\":\"tipo_bien\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"TXTIPOBIENINMUEBLE\"},{\"name\":\"ubicacion_ubigeo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ubicacion_pais\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ubicacion_departamento\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ubicacion_provincia\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ubicacion_distrito\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ubicacion_direccion\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"sunarp_tiene\",\"type\":\"boolean\"},{\"name\":\"sunarp_partida\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"comentario\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"auto_valuo\",\"type\":\"double\",\"doc\":\"FLAUTOVALUO\"},{\"name\":\"uit\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BienInmueble> ENCODER =
      new BinaryMessageEncoder<BienInmueble>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BienInmueble> DECODER =
      new BinaryMessageDecoder<BienInmueble>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BienInmueble> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BienInmueble> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BienInmueble> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BienInmueble>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BienInmueble to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BienInmueble from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BienInmueble instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BienInmueble fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** TXTIPOBIENINMUEBLE */
   private java.lang.String tipo_bien;
   private java.lang.String ubicacion_ubigeo;
   private java.lang.String ubicacion_pais;
   private java.lang.String ubicacion_departamento;
   private java.lang.String ubicacion_provincia;
   private java.lang.String ubicacion_distrito;
   private java.lang.String ubicacion_direccion;
   private boolean sunarp_tiene;
   private java.lang.String sunarp_partida;
   private java.lang.String comentario;
  /** FLAUTOVALUO */
   private double auto_valuo;
   private double uit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BienInmueble() {}

  /**
   * All-args constructor.
   * @param tipo_bien TXTIPOBIENINMUEBLE
   * @param ubicacion_ubigeo The new value for ubicacion_ubigeo
   * @param ubicacion_pais The new value for ubicacion_pais
   * @param ubicacion_departamento The new value for ubicacion_departamento
   * @param ubicacion_provincia The new value for ubicacion_provincia
   * @param ubicacion_distrito The new value for ubicacion_distrito
   * @param ubicacion_direccion The new value for ubicacion_direccion
   * @param sunarp_tiene The new value for sunarp_tiene
   * @param sunarp_partida The new value for sunarp_partida
   * @param comentario The new value for comentario
   * @param auto_valuo FLAUTOVALUO
   * @param uit The new value for uit
   */
  public BienInmueble(java.lang.String tipo_bien, java.lang.String ubicacion_ubigeo, java.lang.String ubicacion_pais, java.lang.String ubicacion_departamento, java.lang.String ubicacion_provincia, java.lang.String ubicacion_distrito, java.lang.String ubicacion_direccion, java.lang.Boolean sunarp_tiene, java.lang.String sunarp_partida, java.lang.String comentario, java.lang.Double auto_valuo, java.lang.Double uit) {
    this.tipo_bien = tipo_bien;
    this.ubicacion_ubigeo = ubicacion_ubigeo;
    this.ubicacion_pais = ubicacion_pais;
    this.ubicacion_departamento = ubicacion_departamento;
    this.ubicacion_provincia = ubicacion_provincia;
    this.ubicacion_distrito = ubicacion_distrito;
    this.ubicacion_direccion = ubicacion_direccion;
    this.sunarp_tiene = sunarp_tiene;
    this.sunarp_partida = sunarp_partida;
    this.comentario = comentario;
    this.auto_valuo = auto_valuo;
    this.uit = uit;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tipo_bien;
    case 1: return ubicacion_ubigeo;
    case 2: return ubicacion_pais;
    case 3: return ubicacion_departamento;
    case 4: return ubicacion_provincia;
    case 5: return ubicacion_distrito;
    case 6: return ubicacion_direccion;
    case 7: return sunarp_tiene;
    case 8: return sunarp_partida;
    case 9: return comentario;
    case 10: return auto_valuo;
    case 11: return uit;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tipo_bien = value$ != null ? value$.toString() : null; break;
    case 1: ubicacion_ubigeo = value$ != null ? value$.toString() : null; break;
    case 2: ubicacion_pais = value$ != null ? value$.toString() : null; break;
    case 3: ubicacion_departamento = value$ != null ? value$.toString() : null; break;
    case 4: ubicacion_provincia = value$ != null ? value$.toString() : null; break;
    case 5: ubicacion_distrito = value$ != null ? value$.toString() : null; break;
    case 6: ubicacion_direccion = value$ != null ? value$.toString() : null; break;
    case 7: sunarp_tiene = (java.lang.Boolean)value$; break;
    case 8: sunarp_partida = value$ != null ? value$.toString() : null; break;
    case 9: comentario = value$ != null ? value$.toString() : null; break;
    case 10: auto_valuo = (java.lang.Double)value$; break;
    case 11: uit = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'tipo_bien' field.
   * @return TXTIPOBIENINMUEBLE
   */
  public java.lang.String getTipoBien() {
    return tipo_bien;
  }


  /**
   * Sets the value of the 'tipo_bien' field.
   * TXTIPOBIENINMUEBLE
   * @param value the value to set.
   */
  public void setTipoBien(java.lang.String value) {
    this.tipo_bien = value;
  }

  /**
   * Gets the value of the 'ubicacion_ubigeo' field.
   * @return The value of the 'ubicacion_ubigeo' field.
   */
  public java.lang.String getUbicacionUbigeo() {
    return ubicacion_ubigeo;
  }


  /**
   * Sets the value of the 'ubicacion_ubigeo' field.
   * @param value the value to set.
   */
  public void setUbicacionUbigeo(java.lang.String value) {
    this.ubicacion_ubigeo = value;
  }

  /**
   * Gets the value of the 'ubicacion_pais' field.
   * @return The value of the 'ubicacion_pais' field.
   */
  public java.lang.String getUbicacionPais() {
    return ubicacion_pais;
  }


  /**
   * Sets the value of the 'ubicacion_pais' field.
   * @param value the value to set.
   */
  public void setUbicacionPais(java.lang.String value) {
    this.ubicacion_pais = value;
  }

  /**
   * Gets the value of the 'ubicacion_departamento' field.
   * @return The value of the 'ubicacion_departamento' field.
   */
  public java.lang.String getUbicacionDepartamento() {
    return ubicacion_departamento;
  }


  /**
   * Sets the value of the 'ubicacion_departamento' field.
   * @param value the value to set.
   */
  public void setUbicacionDepartamento(java.lang.String value) {
    this.ubicacion_departamento = value;
  }

  /**
   * Gets the value of the 'ubicacion_provincia' field.
   * @return The value of the 'ubicacion_provincia' field.
   */
  public java.lang.String getUbicacionProvincia() {
    return ubicacion_provincia;
  }


  /**
   * Sets the value of the 'ubicacion_provincia' field.
   * @param value the value to set.
   */
  public void setUbicacionProvincia(java.lang.String value) {
    this.ubicacion_provincia = value;
  }

  /**
   * Gets the value of the 'ubicacion_distrito' field.
   * @return The value of the 'ubicacion_distrito' field.
   */
  public java.lang.String getUbicacionDistrito() {
    return ubicacion_distrito;
  }


  /**
   * Sets the value of the 'ubicacion_distrito' field.
   * @param value the value to set.
   */
  public void setUbicacionDistrito(java.lang.String value) {
    this.ubicacion_distrito = value;
  }

  /**
   * Gets the value of the 'ubicacion_direccion' field.
   * @return The value of the 'ubicacion_direccion' field.
   */
  public java.lang.String getUbicacionDireccion() {
    return ubicacion_direccion;
  }


  /**
   * Sets the value of the 'ubicacion_direccion' field.
   * @param value the value to set.
   */
  public void setUbicacionDireccion(java.lang.String value) {
    this.ubicacion_direccion = value;
  }

  /**
   * Gets the value of the 'sunarp_tiene' field.
   * @return The value of the 'sunarp_tiene' field.
   */
  public boolean getSunarpTiene() {
    return sunarp_tiene;
  }


  /**
   * Sets the value of the 'sunarp_tiene' field.
   * @param value the value to set.
   */
  public void setSunarpTiene(boolean value) {
    this.sunarp_tiene = value;
  }

  /**
   * Gets the value of the 'sunarp_partida' field.
   * @return The value of the 'sunarp_partida' field.
   */
  public java.lang.String getSunarpPartida() {
    return sunarp_partida;
  }


  /**
   * Sets the value of the 'sunarp_partida' field.
   * @param value the value to set.
   */
  public void setSunarpPartida(java.lang.String value) {
    this.sunarp_partida = value;
  }

  /**
   * Gets the value of the 'comentario' field.
   * @return The value of the 'comentario' field.
   */
  public java.lang.String getComentario() {
    return comentario;
  }


  /**
   * Sets the value of the 'comentario' field.
   * @param value the value to set.
   */
  public void setComentario(java.lang.String value) {
    this.comentario = value;
  }

  /**
   * Gets the value of the 'auto_valuo' field.
   * @return FLAUTOVALUO
   */
  public double getAutoValuo() {
    return auto_valuo;
  }


  /**
   * Sets the value of the 'auto_valuo' field.
   * FLAUTOVALUO
   * @param value the value to set.
   */
  public void setAutoValuo(double value) {
    this.auto_valuo = value;
  }

  /**
   * Gets the value of the 'uit' field.
   * @return The value of the 'uit' field.
   */
  public double getUit() {
    return uit;
  }


  /**
   * Sets the value of the 'uit' field.
   * @param value the value to set.
   */
  public void setUit(double value) {
    this.uit = value;
  }

  /**
   * Creates a new BienInmueble RecordBuilder.
   * @return A new BienInmueble RecordBuilder
   */
  public static openpolitica.jne.elecciones.data.BienInmueble.Builder newBuilder() {
    return new openpolitica.jne.elecciones.data.BienInmueble.Builder();
  }

  /**
   * Creates a new BienInmueble RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BienInmueble RecordBuilder
   */
  public static openpolitica.jne.elecciones.data.BienInmueble.Builder newBuilder(openpolitica.jne.elecciones.data.BienInmueble.Builder other) {
    if (other == null) {
      return new openpolitica.jne.elecciones.data.BienInmueble.Builder();
    } else {
      return new openpolitica.jne.elecciones.data.BienInmueble.Builder(other);
    }
  }

  /**
   * Creates a new BienInmueble RecordBuilder by copying an existing BienInmueble instance.
   * @param other The existing instance to copy.
   * @return A new BienInmueble RecordBuilder
   */
  public static openpolitica.jne.elecciones.data.BienInmueble.Builder newBuilder(openpolitica.jne.elecciones.data.BienInmueble other) {
    if (other == null) {
      return new openpolitica.jne.elecciones.data.BienInmueble.Builder();
    } else {
      return new openpolitica.jne.elecciones.data.BienInmueble.Builder(other);
    }
  }

  /**
   * RecordBuilder for BienInmueble instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BienInmueble>
    implements org.apache.avro.data.RecordBuilder<BienInmueble> {

    /** TXTIPOBIENINMUEBLE */
    private java.lang.String tipo_bien;
    private java.lang.String ubicacion_ubigeo;
    private java.lang.String ubicacion_pais;
    private java.lang.String ubicacion_departamento;
    private java.lang.String ubicacion_provincia;
    private java.lang.String ubicacion_distrito;
    private java.lang.String ubicacion_direccion;
    private boolean sunarp_tiene;
    private java.lang.String sunarp_partida;
    private java.lang.String comentario;
    /** FLAUTOVALUO */
    private double auto_valuo;
    private double uit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(openpolitica.jne.elecciones.data.BienInmueble.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tipo_bien)) {
        this.tipo_bien = data().deepCopy(fields()[0].schema(), other.tipo_bien);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.ubicacion_ubigeo)) {
        this.ubicacion_ubigeo = data().deepCopy(fields()[1].schema(), other.ubicacion_ubigeo);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ubicacion_pais)) {
        this.ubicacion_pais = data().deepCopy(fields()[2].schema(), other.ubicacion_pais);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.ubicacion_departamento)) {
        this.ubicacion_departamento = data().deepCopy(fields()[3].schema(), other.ubicacion_departamento);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.ubicacion_provincia)) {
        this.ubicacion_provincia = data().deepCopy(fields()[4].schema(), other.ubicacion_provincia);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.ubicacion_distrito)) {
        this.ubicacion_distrito = data().deepCopy(fields()[5].schema(), other.ubicacion_distrito);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.ubicacion_direccion)) {
        this.ubicacion_direccion = data().deepCopy(fields()[6].schema(), other.ubicacion_direccion);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.sunarp_tiene)) {
        this.sunarp_tiene = data().deepCopy(fields()[7].schema(), other.sunarp_tiene);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.sunarp_partida)) {
        this.sunarp_partida = data().deepCopy(fields()[8].schema(), other.sunarp_partida);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.comentario)) {
        this.comentario = data().deepCopy(fields()[9].schema(), other.comentario);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.auto_valuo)) {
        this.auto_valuo = data().deepCopy(fields()[10].schema(), other.auto_valuo);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.uit)) {
        this.uit = data().deepCopy(fields()[11].schema(), other.uit);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing BienInmueble instance
     * @param other The existing instance to copy.
     */
    private Builder(openpolitica.jne.elecciones.data.BienInmueble other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.tipo_bien)) {
        this.tipo_bien = data().deepCopy(fields()[0].schema(), other.tipo_bien);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ubicacion_ubigeo)) {
        this.ubicacion_ubigeo = data().deepCopy(fields()[1].schema(), other.ubicacion_ubigeo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ubicacion_pais)) {
        this.ubicacion_pais = data().deepCopy(fields()[2].schema(), other.ubicacion_pais);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ubicacion_departamento)) {
        this.ubicacion_departamento = data().deepCopy(fields()[3].schema(), other.ubicacion_departamento);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ubicacion_provincia)) {
        this.ubicacion_provincia = data().deepCopy(fields()[4].schema(), other.ubicacion_provincia);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ubicacion_distrito)) {
        this.ubicacion_distrito = data().deepCopy(fields()[5].schema(), other.ubicacion_distrito);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ubicacion_direccion)) {
        this.ubicacion_direccion = data().deepCopy(fields()[6].schema(), other.ubicacion_direccion);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.sunarp_tiene)) {
        this.sunarp_tiene = data().deepCopy(fields()[7].schema(), other.sunarp_tiene);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.sunarp_partida)) {
        this.sunarp_partida = data().deepCopy(fields()[8].schema(), other.sunarp_partida);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.comentario)) {
        this.comentario = data().deepCopy(fields()[9].schema(), other.comentario);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.auto_valuo)) {
        this.auto_valuo = data().deepCopy(fields()[10].schema(), other.auto_valuo);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.uit)) {
        this.uit = data().deepCopy(fields()[11].schema(), other.uit);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'tipo_bien' field.
      * TXTIPOBIENINMUEBLE
      * @return The value.
      */
    public java.lang.String getTipoBien() {
      return tipo_bien;
    }


    /**
      * Sets the value of the 'tipo_bien' field.
      * TXTIPOBIENINMUEBLE
      * @param value The value of 'tipo_bien'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setTipoBien(java.lang.String value) {
      validate(fields()[0], value);
      this.tipo_bien = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tipo_bien' field has been set.
      * TXTIPOBIENINMUEBLE
      * @return True if the 'tipo_bien' field has been set, false otherwise.
      */
    public boolean hasTipoBien() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tipo_bien' field.
      * TXTIPOBIENINMUEBLE
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearTipoBien() {
      tipo_bien = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ubicacion_ubigeo' field.
      * @return The value.
      */
    public java.lang.String getUbicacionUbigeo() {
      return ubicacion_ubigeo;
    }


    /**
      * Sets the value of the 'ubicacion_ubigeo' field.
      * @param value The value of 'ubicacion_ubigeo'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setUbicacionUbigeo(java.lang.String value) {
      validate(fields()[1], value);
      this.ubicacion_ubigeo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ubicacion_ubigeo' field has been set.
      * @return True if the 'ubicacion_ubigeo' field has been set, false otherwise.
      */
    public boolean hasUbicacionUbigeo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ubicacion_ubigeo' field.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearUbicacionUbigeo() {
      ubicacion_ubigeo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ubicacion_pais' field.
      * @return The value.
      */
    public java.lang.String getUbicacionPais() {
      return ubicacion_pais;
    }


    /**
      * Sets the value of the 'ubicacion_pais' field.
      * @param value The value of 'ubicacion_pais'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setUbicacionPais(java.lang.String value) {
      validate(fields()[2], value);
      this.ubicacion_pais = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ubicacion_pais' field has been set.
      * @return True if the 'ubicacion_pais' field has been set, false otherwise.
      */
    public boolean hasUbicacionPais() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ubicacion_pais' field.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearUbicacionPais() {
      ubicacion_pais = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ubicacion_departamento' field.
      * @return The value.
      */
    public java.lang.String getUbicacionDepartamento() {
      return ubicacion_departamento;
    }


    /**
      * Sets the value of the 'ubicacion_departamento' field.
      * @param value The value of 'ubicacion_departamento'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setUbicacionDepartamento(java.lang.String value) {
      validate(fields()[3], value);
      this.ubicacion_departamento = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ubicacion_departamento' field has been set.
      * @return True if the 'ubicacion_departamento' field has been set, false otherwise.
      */
    public boolean hasUbicacionDepartamento() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ubicacion_departamento' field.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearUbicacionDepartamento() {
      ubicacion_departamento = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'ubicacion_provincia' field.
      * @return The value.
      */
    public java.lang.String getUbicacionProvincia() {
      return ubicacion_provincia;
    }


    /**
      * Sets the value of the 'ubicacion_provincia' field.
      * @param value The value of 'ubicacion_provincia'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setUbicacionProvincia(java.lang.String value) {
      validate(fields()[4], value);
      this.ubicacion_provincia = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'ubicacion_provincia' field has been set.
      * @return True if the 'ubicacion_provincia' field has been set, false otherwise.
      */
    public boolean hasUbicacionProvincia() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'ubicacion_provincia' field.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearUbicacionProvincia() {
      ubicacion_provincia = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'ubicacion_distrito' field.
      * @return The value.
      */
    public java.lang.String getUbicacionDistrito() {
      return ubicacion_distrito;
    }


    /**
      * Sets the value of the 'ubicacion_distrito' field.
      * @param value The value of 'ubicacion_distrito'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setUbicacionDistrito(java.lang.String value) {
      validate(fields()[5], value);
      this.ubicacion_distrito = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'ubicacion_distrito' field has been set.
      * @return True if the 'ubicacion_distrito' field has been set, false otherwise.
      */
    public boolean hasUbicacionDistrito() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'ubicacion_distrito' field.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearUbicacionDistrito() {
      ubicacion_distrito = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'ubicacion_direccion' field.
      * @return The value.
      */
    public java.lang.String getUbicacionDireccion() {
      return ubicacion_direccion;
    }


    /**
      * Sets the value of the 'ubicacion_direccion' field.
      * @param value The value of 'ubicacion_direccion'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setUbicacionDireccion(java.lang.String value) {
      validate(fields()[6], value);
      this.ubicacion_direccion = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'ubicacion_direccion' field has been set.
      * @return True if the 'ubicacion_direccion' field has been set, false otherwise.
      */
    public boolean hasUbicacionDireccion() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'ubicacion_direccion' field.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearUbicacionDireccion() {
      ubicacion_direccion = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'sunarp_tiene' field.
      * @return The value.
      */
    public boolean getSunarpTiene() {
      return sunarp_tiene;
    }


    /**
      * Sets the value of the 'sunarp_tiene' field.
      * @param value The value of 'sunarp_tiene'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setSunarpTiene(boolean value) {
      validate(fields()[7], value);
      this.sunarp_tiene = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'sunarp_tiene' field has been set.
      * @return True if the 'sunarp_tiene' field has been set, false otherwise.
      */
    public boolean hasSunarpTiene() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'sunarp_tiene' field.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearSunarpTiene() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'sunarp_partida' field.
      * @return The value.
      */
    public java.lang.String getSunarpPartida() {
      return sunarp_partida;
    }


    /**
      * Sets the value of the 'sunarp_partida' field.
      * @param value The value of 'sunarp_partida'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setSunarpPartida(java.lang.String value) {
      validate(fields()[8], value);
      this.sunarp_partida = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'sunarp_partida' field has been set.
      * @return True if the 'sunarp_partida' field has been set, false otherwise.
      */
    public boolean hasSunarpPartida() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'sunarp_partida' field.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearSunarpPartida() {
      sunarp_partida = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'comentario' field.
      * @return The value.
      */
    public java.lang.String getComentario() {
      return comentario;
    }


    /**
      * Sets the value of the 'comentario' field.
      * @param value The value of 'comentario'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setComentario(java.lang.String value) {
      validate(fields()[9], value);
      this.comentario = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'comentario' field has been set.
      * @return True if the 'comentario' field has been set, false otherwise.
      */
    public boolean hasComentario() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'comentario' field.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearComentario() {
      comentario = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'auto_valuo' field.
      * FLAUTOVALUO
      * @return The value.
      */
    public double getAutoValuo() {
      return auto_valuo;
    }


    /**
      * Sets the value of the 'auto_valuo' field.
      * FLAUTOVALUO
      * @param value The value of 'auto_valuo'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setAutoValuo(double value) {
      validate(fields()[10], value);
      this.auto_valuo = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'auto_valuo' field has been set.
      * FLAUTOVALUO
      * @return True if the 'auto_valuo' field has been set, false otherwise.
      */
    public boolean hasAutoValuo() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'auto_valuo' field.
      * FLAUTOVALUO
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearAutoValuo() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'uit' field.
      * @return The value.
      */
    public double getUit() {
      return uit;
    }


    /**
      * Sets the value of the 'uit' field.
      * @param value The value of 'uit'.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder setUit(double value) {
      validate(fields()[11], value);
      this.uit = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'uit' field has been set.
      * @return True if the 'uit' field has been set, false otherwise.
      */
    public boolean hasUit() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'uit' field.
      * @return This builder.
      */
    public openpolitica.jne.elecciones.data.BienInmueble.Builder clearUit() {
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BienInmueble build() {
      try {
        BienInmueble record = new BienInmueble();
        record.tipo_bien = fieldSetFlags()[0] ? this.tipo_bien : (java.lang.String) defaultValue(fields()[0]);
        record.ubicacion_ubigeo = fieldSetFlags()[1] ? this.ubicacion_ubigeo : (java.lang.String) defaultValue(fields()[1]);
        record.ubicacion_pais = fieldSetFlags()[2] ? this.ubicacion_pais : (java.lang.String) defaultValue(fields()[2]);
        record.ubicacion_departamento = fieldSetFlags()[3] ? this.ubicacion_departamento : (java.lang.String) defaultValue(fields()[3]);
        record.ubicacion_provincia = fieldSetFlags()[4] ? this.ubicacion_provincia : (java.lang.String) defaultValue(fields()[4]);
        record.ubicacion_distrito = fieldSetFlags()[5] ? this.ubicacion_distrito : (java.lang.String) defaultValue(fields()[5]);
        record.ubicacion_direccion = fieldSetFlags()[6] ? this.ubicacion_direccion : (java.lang.String) defaultValue(fields()[6]);
        record.sunarp_tiene = fieldSetFlags()[7] ? this.sunarp_tiene : (java.lang.Boolean) defaultValue(fields()[7]);
        record.sunarp_partida = fieldSetFlags()[8] ? this.sunarp_partida : (java.lang.String) defaultValue(fields()[8]);
        record.comentario = fieldSetFlags()[9] ? this.comentario : (java.lang.String) defaultValue(fields()[9]);
        record.auto_valuo = fieldSetFlags()[10] ? this.auto_valuo : (java.lang.Double) defaultValue(fields()[10]);
        record.uit = fieldSetFlags()[11] ? this.uit : (java.lang.Double) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BienInmueble>
    WRITER$ = (org.apache.avro.io.DatumWriter<BienInmueble>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BienInmueble>
    READER$ = (org.apache.avro.io.DatumReader<BienInmueble>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.tipo_bien);

    out.writeString(this.ubicacion_ubigeo);

    out.writeString(this.ubicacion_pais);

    out.writeString(this.ubicacion_departamento);

    out.writeString(this.ubicacion_provincia);

    out.writeString(this.ubicacion_distrito);

    out.writeString(this.ubicacion_direccion);

    out.writeBoolean(this.sunarp_tiene);

    out.writeString(this.sunarp_partida);

    out.writeString(this.comentario);

    out.writeDouble(this.auto_valuo);

    out.writeDouble(this.uit);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tipo_bien = in.readString();

      this.ubicacion_ubigeo = in.readString();

      this.ubicacion_pais = in.readString();

      this.ubicacion_departamento = in.readString();

      this.ubicacion_provincia = in.readString();

      this.ubicacion_distrito = in.readString();

      this.ubicacion_direccion = in.readString();

      this.sunarp_tiene = in.readBoolean();

      this.sunarp_partida = in.readString();

      this.comentario = in.readString();

      this.auto_valuo = in.readDouble();

      this.uit = in.readDouble();

    } else {
      for (int i = 0; i < 12; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tipo_bien = in.readString();
          break;

        case 1:
          this.ubicacion_ubigeo = in.readString();
          break;

        case 2:
          this.ubicacion_pais = in.readString();
          break;

        case 3:
          this.ubicacion_departamento = in.readString();
          break;

        case 4:
          this.ubicacion_provincia = in.readString();
          break;

        case 5:
          this.ubicacion_distrito = in.readString();
          break;

        case 6:
          this.ubicacion_direccion = in.readString();
          break;

        case 7:
          this.sunarp_tiene = in.readBoolean();
          break;

        case 8:
          this.sunarp_partida = in.readString();
          break;

        case 9:
          this.comentario = in.readString();
          break;

        case 10:
          this.auto_valuo = in.readDouble();
          break;

        case 11:
          this.uit = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










