# This is a basic workflow to help you get started with Actions
name: extract

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  etl:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Build project with Maven
        run: mvn clean compile

      - name: Run extraction
        run: mvn exec:java -D"exec.mainClass"="openpolitica.jne.CandidatosEtl2021"

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: main
          message: 'workflow: datos actualizados'
          github_token: ${{ secrets.GITHUB_TOKEN }}